export DISABLE_AUTO_TITLE="true"

# Python
export PATH=$HOME/Library/Python/2.7/bin:$PATH
export PYTHONPATH=$HOME/Library/Python/2.7/lib/python/site-packages:$PYTHONPATH

# Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Clang
export ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"

# Enable bash-style comments
setopt interactivecomments

# pyenv setup
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Terminal aliases and functions
alias o="open"
function c() { cd "$@"; ls; }
alias notify="osascript -e 'display notification with title \"Job complete.\"'"

# Shortcut aliases
alias chrome-dev="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --allow-file-access-from-files"

# MacVim aliases
#alias v="mvim"

# ChetanSurpur.com aliases
alias chetansurpur="ssh root@chetansurpur.com"

# Mac aliases
alias ql="qlmanage -p"

# Postgres
export PGDATA=/Library/PostgreSQL/9.1/data

# Octave
export GNUTERM=x11

# Hadoop
alias hadoop-start="/usr/local/Cellar/hadoop/1.0.3/bin/start-all.sh"
alias hadoop-stop="/usr/local/Cellar/hadoop/1.0.3/bin/stop-all.sh"

# Fasd
eval "$(fasd --init posix-alias zsh-hook)"

# Sublime Text aliases
alias s="subl -n ."

# Git aliases
alias git=hub
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gpr="git pull --rebase"
alias gpu="git push"

# NuPIC
export NUPIC=$HOME/Dropbox/Development/nupic

# Keys
# source $HOME/.keys

# Taurus
export TAURUS_RMQ_METRIC_DEST="127.0.0.1:2003"
#export TAURUS_HTM_SERVER="127.0.0.1"
export APPLICATION_CONFIG_PATH=/Users/Chetan/Dropbox/Development/products/taurus/conf-user

# AWS
# source $HOME/.aws/.awsrc

# rbenv
# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"

# nvm
. ~/.nvm/nvm.sh

# Powerline
if [[ -r ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh ]]; then
    source ~/.local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Docker
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/Chetan/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

# SCM Breeze
[ -s "$HOME/.scm_breeze/scm_breeze.sh" ] && source "$HOME/.scm_breeze/scm_breeze.sh"


[ -s "/Users/Chetan/.scm_breeze/scm_breeze.sh" ] && source "/Users/Chetan/.scm_breeze/scm_breeze.sh"
