# Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Clang
export ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"

# Enable bash-style comments
setopt interactivecomments

# pyenv setup
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Terminal aliases and functions
alias o="open"
function c() { cd "$@"; ls; }

# Shortcut aliases
alias chrome-dev="/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --allow-file-access-from-files"

# MacVim aliases
#alias v="mvim"

# ChetanSurpur.com aliases
alias chetansurpur="ssh root@chetansurpur.com"

# Mac aliases
alias ql="qlmanage -p"

# Postgres
export PGDATA=/Library/PostgreSQL/9.1/data

# Octave
export GNUTERM=x11

# Hadoop
alias hadoop-start="/usr/local/Cellar/hadoop/1.0.3/bin/start-all.sh"
alias hadoop-stop="/usr/local/Cellar/hadoop/1.0.3/bin/stop-all.sh"

# Python
export PYTHONPATH=$PYTHONPATH:$HOME/.local/lib/python2.7/site-packages

# Fasd
eval "$(fasd --init posix-alias zsh-hook)"

# Sublime Text aliases
alias s="subl -n ."

# Git aliases
alias git=hub
alias gl="git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gpr="git pull --rebase"
alias gpu="git push"

# Go
export GOPATH=~/Development/go

# NuPIC
export NUPIC=$HOME/Development/nupic

# Grok
source $HOME/.grok/.grokrc

# AWS
source $HOME/.aws/.awsrc

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# nvm
. ~/.nvm/nvm.sh

# SCM Breeze
[ -s "$HOME/.scm_breeze/scm_breeze.sh" ] && source "$HOME/.scm_breeze/scm_breeze.sh"
